### PR TITLE
Performance and organizational improvements

### PR DESCRIPTION
**Pull request by KeaunAmani**
Added a feature so that users can directly provide their MSAs instead of having to compute them each time from a set of reference sequences.

Also refactored much of the code in `src/pgen/likelihood_esm_msa.py` to execute more smoothly and made it cleaner from an organizational standpoint.

### CODE REVIEW

**Comment by seanrjohnson** [comment]
It would be good to document where the target sequence is expected to be in `in_msas`, because it is the end sequence, not the top sequence, so if taking MSAs directly from ColabFold, for example, the target sequence will have to be swapped from the top of the MSA to the bottom (maybe there could be a parameter to swap within the function)? Also documenting how `in_msas` interacts with `input_h`, would be good. Basically how are users expected to use that input parameter?

A bigger issue I see is that I think this PR reduces memory efficiency, which could be a problem for large inputs. For example if the user supplies a long list, like thousands, of input sequences, then it looks like this code will pre-generate MSAs for all of them, even though it will only calculate scores for one MSA at a time. So there will be a lot of MSAs in memory that don't need to be there.

It would be better to change the conditional block under `if generate_msas:` into a generator and only generate and sample one msa at a time.

**Comment by KeaunAmani** [comment]
@seanrjohnson smart! I updated the comments to explain this in detail. Personally an additional flag for moving the first sequence to the end of each MSA seems completely unnecessary as anybody who is using the programmatic API at that level should be able to figure that out.

Also `in_msas` does not impact `input_h` currently.

As for loading all the MSAs into memory directly, it's really not that big of a deal even when you have over 20k MSAs and this is done intentionally to keep things consistent with the `in_msas` parameter that passes in all the MSAs directly anyways.

**Comment by KeaunAmani** [comment]
I just did a test and loaded 3075 MSAs into `in_msas` where each MSA contains 32 sequences of length 100 and found that the entire object amounted to a total of 15mb. Even if we quadrupled the amount of sequences as well as the lengths of each sequence. The entire object wouldn't even reach 100mb in size.

I think this is a very reasonable sacrifice to make for making the code more concise as well as adding a much needed feature.

**Comment by seanrjohnson** [comment]
Here is what GPT-4 suggests:

You can use a generator to lazily populate `in_msas` as they are consumed in the line `tmp_msa_list = [in_msas[x] for x in batch]`. First, I will define a generator function `get_in_msa` that takes the sequence name and returns the corresponding MSA. Then, I will replace the line where `tmp_msa_list` is created with a list comprehension that calls the generator function for each name in the batch.

I think in this case `get_in_msa` is a subfunction in `main`.
```python
def get_in_msa(name):
    if generate_msas:
        # generate msa using top_hits from reference sequences
        if subset_strategy == "top_hits":
            hits = run_phmmer(seq, reference_db_path)
            # mafft should preserve the order of sequences
            _, new_alignment = generate_alignment({"1": [renamed_reference_sequences[hit] for hit in hits[:alignment_size]] + [seq]})
            return new_alignment
        else:
            if redraw:
                seq_msa = SequenceSubsetter.subset(reference_msa, alignment_size, strategy=subset_strategy, random_seed=subset_random_seed)
                if subset_random_seed is not None:
                    subset_random_seed += 1000000
            if unaligned_queries:
                return add_to_msa(seq_msa, seq)
            else:
                return seq_msa.copy() + [seq]
    else:
        return in_msas[name]

# ... (rest of the code remains the same)

for batch in tqdm.tqdm(batch(list(in_seqs.keys()), batch_size), total=len(in_seqs)):
    tmp_name_list = batch
    tmp_msa_list = [get_in_msa(x) for x in batch]

# ... (rest of the code remains the same)
```

This modification ensures that the `in_msas` dictionary is populated lazily as each MSA is consumed.

**Comment by KeaunAmani** [comment]
Yeah seems reasonable to me. I implemented the code above but I haven't tested it. The test is running now.

**Comment by seanrjohnson** [comment]
Thanks.

**Pull request merged**
